// Catálogo clínico interno de parámetros de laboratorio
// Nota: Rangos orientativos; deben validarse según población y método local.

module.exports = {
  version: '2025.10.05-chem4',
  updatedAt: '2025-10-05T04:30:00Z',
  parameters: [
    {
      key: 'vcm',
      canonicalName: 'Volumen Corpuscular Medio',
      synonyms: ['vcm','mcv','volumen corpuscular medio'],
      unit: 'fL',
      decimal_places: 1,
      method: 'Analizador Hematológico Automático',
      assayNotes: 'Método basado en impedancia o láser según equipo.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:1, lower:84, upper:106 },
        { sex:'Ambos', min:1, max:2, lower:72, upper:84 },
        { sex:'Ambos', min:2, max:12, lower:76, upper:90 },
        { sex:'Ambos', min:12, max:18, lower:78, upper:95 },
        { sex:'Femenino', min:18, max:120, lower:80, upper:96 },
        { sex:'Masculino', min:18, max:120, lower:80, upper:96 }
      ],
      notes: 'Rangos hematológicos estándar aproximados.',
      sources: [ { citation: 'Ref. Hematología estándar', url: '' } ],
      categoryHints: ['Biometría Hemática','Hemograma']
    },
    {
      key: 'hcm',
      canonicalName: 'Hemoglobina Corpuscular Media',
      synonyms: ['hcm','mch','hemoglobina corpuscular media'],
      unit: 'pg',
      decimal_places: 1,
      method: 'Analizador Hematológico Automático',
      assayNotes: 'Derivado de Hb y recuento eritrocitario.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:1, lower:28, upper:40 },
        { sex:'Ambos', min:1, max:2, lower:23, upper:31 },
        { sex:'Ambos', min:2, max:12, lower:25, upper:33 },
        { sex:'Ambos', min:12, max:18, lower:26, upper:34 },
        { sex:'Femenino', min:18, max:120, lower:27, upper:33 },
        { sex:'Masculino', min:18, max:120, lower:27, upper:33 }
      ],
      notes: 'Rangos aproximados; verificar con equipo local.',
      sources: [ { citation: 'Ref. Hematología estándar', url: '' } ],
      categoryHints: ['Biometría Hemática','Hemograma']
    },
    {
      key: 'rdw',
      canonicalName: 'Amplitud de Distribución Eritrocitaria',
      synonyms: ['rdw','amplitud de distribucion eritrocitaria'],
      unit: '%',
      decimal_places: 1,
      method: 'Analizador Hematológico Automático',
      assayNotes: 'Cálculo estadístico de variabilidad del VCM.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:1, lower:14, upper:18 },
        { sex:'Ambos', min:1, max:2, lower:12.5, upper:15.5 },
        { sex:'Ambos', min:2, max:12, lower:11.5, upper:14.5 },
        { sex:'Ambos', min:12, max:120, lower:11, upper:14.5 }
      ],
      notes: 'Rangos orientativos; variaciones según analizador.',
      sources: [ { citation: 'Ref. Hematología estándar', url: '' } ],
      categoryHints: ['Biometría Hemática','Hemograma']
    },
    // ================== QUÍMICA CLÍNICA GENERAL ==================
    {
      key: 'glucosa',
      canonicalName: 'Glucosa',
      synonyms: ['glucosa','glucose','glycemia','glicemia'],
      unit: 'mg/dL',
      decimal_places: 0,
      method: 'Hexoquinasa',
      assayNotes: 'Plasma en fluoruro/oxalato preferente.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:2, lower:60, upper:110 },
        { sex:'Ambos', min:2, max:12, lower:70, upper:105 },
        { sex:'Ambos', min:12, max:120, lower:70, upper:99 }
      ],
      notes: 'Valores en ayuno; pueden variar según guía clínica.',
      sources: [ { citation: 'ADA / Guías estándar', url:'' } ],
      categoryHints: ['Química Sanguínea','Metabólico']
    },
    {
      key: 'urea',
      canonicalName: 'Urea',
      synonyms: ['urea','bun'],
      unit: 'mg/dL',
      decimal_places: 0,
      method: 'Ureasa',
      assayNotes: 'Conversión a amonio medido fotométricamente.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:1, lower:3, upper:18 },
        { sex:'Ambos', min:1, max:12, lower:7, upper:20 },
        { sex:'Ambos', min:12, max:120, lower:10, upper:40 }
      ],
      notes: 'Equivalente aproximado BUN. Ajustar según método.',
      sources: [ { citation: 'Ref. Bioquímica estándar', url:'' } ],
      categoryHints: ['Química Sanguínea','Renal']
    },
    {
      key: 'creatinina',
      canonicalName: 'Creatinina',
      synonyms: ['creatinina','creatinine'],
      unit: 'mg/dL',
      decimal_places: 2,
      method: 'Enzimático',
      assayNotes: 'Evita interferencias típicas del método Jaffé.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:1, lower:0.20, upper:0.50 },
        { sex:'Ambos', min:1, max:12, lower:0.30, upper:0.70 },
        { sex:'Femenino', min:12, max:120, lower:0.50, upper:1.00 },
        { sex:'Masculino', min:12, max:120, lower:0.60, upper:1.20 }
      ],
      notes: 'Método enzimático/Jaffé compensado.',
      sources: [ { citation: 'KDIGO orientativo', url:'' } ],
      categoryHints: ['Química Sanguínea','Renal']
    },
    {
      key: 'acido_urico',
      canonicalName: 'Ácido Úrico',
      synonyms: ['acido urico','ácido úrico','uric acid'],
      unit: 'mg/dL',
      decimal_places: 1,
      method: 'Uricasa',
      assayNotes: 'Método enzimático colorimétrico.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:12, lower:2.0, upper:5.5 },
        { sex:'Femenino', min:12, max:120, lower:2.4, upper:6.0 },
        { sex:'Masculino', min:12, max:120, lower:3.4, upper:7.0 }
      ],
      notes: 'Valores adultos pueden variar según dieta.',
      sources: [ { citation: 'Ref. Bioquímica estándar', url:'' } ],
      categoryHints: ['Química Sanguínea','Metabólico']
    },
    {
      key: 'colesterol_total',
      canonicalName: 'Colesterol Total',
      synonyms: ['colesterol total','cholesterol total','chol total'],
      unit: 'mg/dL',
      decimal_places: 0,
      method: 'Enzimático colorimétrico',
      assayNotes: 'Colesterol esterasas/oxidasa.',
      validated: true,
      lockAI: true,
      groups: [
        { sex:'Ambos', min:0, max:12, lower:120, upper:200 },
        { sex:'Ambos', min:12, max:120, lower:125, upper:200 }
      ],
      notes: 'Adulto: <200 deseable (NCEP).',
      sources: [ { citation: 'NCEP ATP III', url:'' } ],
      categoryHints: ['Perfil Lipídico']
    },
    {
      key:'hdl',
      canonicalName:'Colesterol HDL',
      synonyms:['hdl','colesterol hdl','hdl colesterol'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Selectivo directo',
      assayNotes:'Método homogéneo sin precipitación.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:12, lower:35, upper:80 },
        { sex:'Femenino', min:12, max:120, lower:50, upper:90 },
        { sex:'Masculino', min:12, max:120, lower:40, upper:80 }
      ],
      notes:'Valores deseables: ≥40 M, ≥50 F.',
      sources:[{ citation:'NCEP ATP III', url:'' }],
      categoryHints:['Perfil Lipídico']
    },
    {
      key:'ldl_calculado',
      canonicalName:'LDL Calculado',
      synonyms:['ldl','ldl calculado','calculated ldl'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Cálculo Friedewald',
      assayNotes:'Requiere TG <400 mg/dL.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:12, max:120, lower:50, upper:129 }
      ],
      notes:'Adulto: <100 óptimo; rango aquí orientativo.',
      sources:[{ citation:'NCEP ATP III', url:'' }],
      categoryHints:['Perfil Lipídico']
    },
    {
      key:'trigliceridos',
      canonicalName:'Triglicéridos',
      synonyms:['trigliceridos','triglicéridos','triglycerides'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Enzimático GPO-PAP',
      assayNotes:'Glicerol enzimático.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:12, lower:30, upper:130 },
        { sex:'Ambos', min:12, max:120, lower:40, upper:149 }
      ],
      notes:'<150 normal en adulto (NCEP).',
      sources:[{ citation:'NCEP ATP III', url:'' }],
      categoryHints:['Perfil Lipídico']
    },
    {
      key:'vldl',
      canonicalName:'VLDL Estimado',
      synonyms:['vldl','vldl estimado'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Estimación',
      assayNotes:'TG/5 (mg/dL).',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:5, upper:30 } ],
      notes:'Estimado (Triglicéridos/5) – rango orientativo.',
      sources:[{ citation:'NCEP ATP III', url:'' }],
      categoryHints:['Perfil Lipídico']
    },
    {
      key:'proteinas_totales',
      canonicalName:'Proteínas Totales',
      synonyms:['proteinas totales','proteínas totales','total protein'],
      unit:'g/dL',
      decimal_places:1,
      method:'Biuret',
      assayNotes:'Complejo cobre-alcalino.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:1, lower:4.6, upper:7.2 },
        { sex:'Ambos', min:1, max:12, lower:5.5, upper:7.8 },
        { sex:'Ambos', min:12, max:120, lower:6.4, upper:8.3 }
      ],
      notes:'Incluye albúmina + globulinas.',
      sources:[{ citation:'Ref. Bioquímica estándar', url:'' }],
      categoryHints:['Química Sanguínea','Hepático']
    },
    {
      key:'albumina',
      canonicalName:'Albúmina',
      synonyms:['albumina','albúmina','albumin'],
      unit:'g/dL',
      decimal_places:1,
      method:'Colorimétrico (verde de bromocresol)',
      assayNotes:'Puede usarse púrpura de bromocresol.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:1, lower:3.4, upper:5.4 },
        { sex:'Ambos', min:1, max:12, lower:3.8, upper:5.4 },
        { sex:'Ambos', min:12, max:120, lower:3.5, upper:5.0 }
      ],
      notes:'Rango adulto típico 3.5–5.0 g/dL.',
      sources:[{ citation:'Ref. Bioquímica estándar', url:'' }],
      categoryHints:['Química Sanguínea','Hepático']
    },
    {
      key:'bilirrubina_total',
      canonicalName:'Bilirrubina Total',
      synonyms:['bilirrubina total','bilirubin total','bt','tbil'],
      unit:'mg/dL',
      decimal_places:2,
      method:'Diazo',
      assayNotes:'Reacción de van den Bergh total.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:0.2, upper:1.2 } ],
      notes:'Adulto sano ~0.2–1.2 mg/dL.',
      sources:[{ citation:'Ref. Hepática estándar', url:'' }],
      categoryHints:['Hepático','Química Sanguínea']
    },
    {
      key:'bilirrubina_directa',
      canonicalName:'Bilirrubina Directa',
      synonyms:['bilirrubina directa','direct bilirubin','dbil'],
      unit:'mg/dL',
      decimal_places:2,
      method:'Diazo fraccionada',
      assayNotes:'Directa conjugada.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:0.0, upper:0.3 } ],
      notes:'Puede variar 0.0–0.2 según método.',
      sources:[{ citation:'Ref. Hepática estándar', url:'' }],
      categoryHints:['Hepático']
    },
    {
      key:'tgo_ast',
      canonicalName:'AST (TGO)',
      synonyms:['ast','tgo','ast (tgo)','aspartato aminotransferasa','sgot','ast/tgo','ast_tgo'],
      unit:'U/L',
      decimal_places:0,
      method:'IFCC',
      assayNotes:'Con P5P preferentemente.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:10, upper:40 } ],
      notes:'Rango adulto 10–40 U/L aprox.',
      sources:[{ citation:'Ref. Hepática estándar', url:'' }],
      categoryHints:['Hepático','Química Sanguínea']
    },
    {
      key:'tgp_alt',
      canonicalName:'ALT (TGP)',
      synonyms:['alt','tgp','alt (tgp)','alanina aminotransferasa','gpt','gpt/alt','sgpt','alt/tgp','alt_tgp'],
      unit:'U/L',
      decimal_places:0,
      method:'IFCC',
      assayNotes:'Con P5P preferentemente.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:7, upper:56 } ],
      notes:'Método IFCC sin P5P puede variar.',
      sources:[{ citation:'Ref. Hepática estándar', url:'' }],
      categoryHints:['Hepático','Química Sanguínea']
    },
    {
      key:'fosfatasa_alcalina',
      canonicalName:'Fosfatasa Alcalina',
      synonyms:['fosfatasa alcalina','alkaline phosphatase','alp','fa'],
      unit:'U/L',
      decimal_places:0,
      method:'Cinetico IFCC',
      assayNotes:'A 37°C.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:1, lower:110, upper:400 },
        { sex:'Ambos', min:1, max:12, lower:130, upper:420 },
        { sex:'Ambos', min:12, max:18, lower:80, upper:300 },
        { sex:'Femenino', min:18, max:120, lower:44, upper:147 },
        { sex:'Masculino', min:18, max:120, lower:44, upper:147 }
      ],
      notes:'Valores pediátricos elevados por crecimiento óseo.',
      sources:[{ citation:'Ref. Bioquímica estándar', url:'' }],
      categoryHints:['Hepático','Óseo','Química Sanguínea']
    },
    // Eliminados duplicados ALT/AST (gpt_alt, ast_tgo) consolidando sinónimos arriba
    // ================== ELECTROLITOS Y MINERALES ==================
    {
      key:'sodio',
      canonicalName:'Sodio',
      synonyms:['sodio','na','na+','sodium'],
      unit:'mmol/L',
      decimal_places:0,
      method:'ISE indirecto',
      assayNotes:'Especificar si es directo.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:135, upper:145 } ],
      notes:'Sodio sérico; rango adulto y pediátrico similar.',
      sources:[{ citation:'Ref. Electrolitos estándar', url:'' }],
      categoryHints:['Electrolitos','Química Sanguínea']
    },
    {
      key:'potasio',
      canonicalName:'Potasio',
      synonyms:['potasio','k','k+','potassium'],
      unit:'mmol/L',
      decimal_places:1,
      method:'ISE',
      assayNotes:'Evitar hemólisis.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:3.5, upper:5.1 } ],
      notes:'Suero/plasma sin hemólisis.',
      sources:[{ citation:'Ref. Electrolitos estándar', url:'' }],
      categoryHints:['Electrolitos','Química Sanguínea']
    },
    {
      key:'cloro',
      canonicalName:'Cloro',
      synonyms:['cloro','cl','cl-','chloride'],
      unit:'mmol/L',
      decimal_places:0,
      method:'ISE',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:98, upper:107 } ],
      notes:'Rango convencional.',
      sources:[{ citation:'Ref. Electrolitos estándar', url:'' }],
      categoryHints:['Electrolitos']
    },
    {
      key:'co2_total',
      canonicalName:'CO2 Total',
      synonyms:['co2 total','tco2','bicarbonato total','co2'],
      unit:'mmol/L',
      decimal_places:0,
      method:'Electrodo/enzimático',
      assayNotes:'Relacionado a bicarbonato.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:22, upper:29 } ],
      notes:'Equivale a bicarbonato sérico aproximado.',
      sources:[{ citation:'Ref. Electrolitos estándar', url:'' }],
      categoryHints:['Electrolitos','Ácido-Base']
    },
    {
      key:'calcio',
      canonicalName:'Calcio',
      synonyms:['calcio','calcium','ca','ca++'],
      unit:'mg/dL',
      decimal_places:2,
      method:'Colorimétrico Arsenazo III',
      assayNotes:'OCP alternativa.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:1, lower:8.8, upper:11.0 },
        { sex:'Ambos', min:1, max:12, lower:8.8, upper:10.8 },
        { sex:'Ambos', min:12, max:120, lower:8.6, upper:10.2 }
      ],
      notes:'Calcio total; corregir por albúmina si hipoalbuminemia.',
      sources:[{ citation:'Ref. Minerales estándar', url:'' }],
      categoryHints:['Electrolitos','Óseo']
    },
    {
      key:'fosforo',
      canonicalName:'Fósforo',
      synonyms:['fosforo','fósforo','phosphorus','p'],
      unit:'mg/dL',
      decimal_places:1,
      method:'Fosfomolibdato UV',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Ambos', min:0, max:1, lower:4.5, upper:6.7 },
        { sex:'Ambos', min:1, max:12, lower:3.5, upper:5.5 },
        { sex:'Ambos', min:12, max:120, lower:2.5, upper:4.5 }
      ],
      notes:'Rangos decrecen con la edad.',
      sources:[{ citation:'Ref. Minerales estándar', url:'' }],
      categoryHints:['Electrolitos','Renal']
    },
    {
      key:'magnesio',
      canonicalName:'Magnesio',
      synonyms:['magnesio','magnesium','mg','mg++'],
      unit:'mg/dL',
      decimal_places:2,
      method:'Colorimétrico Xylidyl blue',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:1.6, upper:2.6 } ],
      notes:'Suero/plasma.',
      sources:[{ citation:'Ref. Minerales estándar', url:'' }],
      categoryHints:['Electrolitos']
    },
    // ================== ENZIMAS Y OTROS ==================
    {
      key:'ggt',
      canonicalName:'GGT',
      synonyms:['γ-gt','gamma gt','ggt','gama gt'],
      unit:'U/L',
      decimal_places:0,
      method:'Cromogénico',
      assayNotes:'Substrato L-γ-glutamil-p-nitroanilida.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Femenino', min:12, max:120, lower:9, upper:36 },
        { sex:'Masculino', min:12, max:120, lower:12, upper:64 }
      ],
      notes:'Valores dependen de consumo alcohólico y fármacos.',
      sources:[{ citation:'Ref. Hepática estándar', url:'' }],
      categoryHints:['Hepático']
    },
    {
      key:'ldh',
      canonicalName:'LDH',
      synonyms:['ldh','lactato deshidrogenasa'],
      unit:'U/L',
      decimal_places:0,
      method:'Cinetico',
      assayNotes:'L->P a 340 nm.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:140, upper:280 } ],
      notes:'Isoenzimas no diferenciadas.',
      sources:[{ citation:'Ref. Enzimas estándar', url:'' }],
      categoryHints:['Metabólico','Hepático']
    },
    {
      key:'amilasa',
      canonicalName:'Amilasa',
      synonyms:['amilasa','amylase'],
      unit:'U/L',
      decimal_places:0,
      method:'Cinetico CNPG3',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:28, upper:100 } ],
      notes:'Suero; métodos CNPG3 varían referencia.',
      sources:[{ citation:'Ref. Pancreática estándar', url:'' }],
      categoryHints:['Pancreático']
    },
    {
      key:'lipasa',
      canonicalName:'Lipasa',
      synonyms:['lipasa','lipase'],
      unit:'U/L',
      decimal_places:0,
      method:'Enzimático colorimétrico',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:13, upper:60 } ],
      notes:'Más específica que amilasa para pancreatitis.',
      sources:[{ citation:'Ref. Pancreática estándar', url:'' }],
      categoryHints:['Pancreático']
    },
    {
      key:'ck_cpk',
      canonicalName:'CK (CPK)',
      synonyms:['ck','cpk','creatin kinasa','creatinfosfoquinasa'],
      unit:'U/L',
      decimal_places:0,
      method:'Cinetico UV',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Femenino', min:12, max:120, lower:38, upper:176 },
        { sex:'Masculino', min:12, max:120, lower:52, upper:336 }
      ],
      notes:'Actividad depende de masa muscular.',
      sources:[{ citation:'Ref. Enzimas estándar', url:'' }],
      categoryHints:['Muscular','Cardíaco']
    },
    // ================== HIERRO Y METABOLISMO ==================
    {
      key:'hierro_serico',
      canonicalName:'Hierro Sérico',
      synonyms:['hierro sérico','hierro serico','serum iron','iron'],
      unit:'µg/dL',
      decimal_places:0,
      method:'Ferrozina',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:60, upper:170 } ],
      notes:'Preferir extracción matutina en ayuno.',
      sources:[{ citation:'Ref. Hierro estándar', url:'' }],
      categoryHints:['Metabolismo Hierro']
    },
    {
      key:'ferritina',
      canonicalName:'Ferritina',
      synonyms:['ferritina','ferritin'],
      unit:'ng/mL',
      decimal_places:0,
      method:'Inmunoensayo (quimioluminiscencia)',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Femenino', min:12, max:120, lower:13, upper:150 },
        { sex:'Masculino', min:12, max:120, lower:30, upper:400 }
      ],
      notes:'Inflamación aguda puede elevar niveles.',
      sources:[{ citation:'Ref. Hierro estándar', url:'' }],
      categoryHints:['Metabolismo Hierro']
    },
    {
      key:'transferrina',
      canonicalName:'Transferrina',
      synonyms:['transferrina','transferrin'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Inmunoturbidimetría',
      assayNotes:'',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:200, upper:360 } ],
      notes:'Aumenta en ferropenia, disminuye en inflamación crónica.',
      sources:[{ citation:'Ref. Hierro estándar', url:'' }],
      categoryHints:['Metabolismo Hierro']
    },
    {
      key:'tibc',
      canonicalName:'TIBC',
      synonyms:['tibc','capacidad total fijacion hierro','total iron binding capacity'],
      unit:'µg/dL',
      decimal_places:0,
      method:'Cálculo',
      assayNotes:'Puede derivarse de transferrina.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:250, upper:450 } ],
      notes:'Se relaciona inversamente con ferritina.',
      sources:[{ citation:'Ref. Hierro estándar', url:'' }],
      categoryHints:['Metabolismo Hierro']
    },
    {
      key:'saturacion_transferrina',
      canonicalName:'Saturación de Transferrina',
      synonyms:['saturacion transferrina','%sat transferrina','transferrin saturation'],
      unit:'%',
      decimal_places:0,
      method:'Cálculo',
      assayNotes:'(Hierro/TIBC)*100%',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:20, upper:50 } ],
      notes:'(Hierro/TIBC)*100%.',
      sources:[{ citation:'Ref. Hierro estándar', url:'' }],
      categoryHints:['Metabolismo Hierro']
    },
    // ================== VITAMINAS ==================
    {
      key:'vitamina_d_25oh',
      canonicalName:'Vitamina D 25-OH',
      synonyms:['vitamina d','25-oh vitamina d','25(oh)d','vitamin d'],
      unit:'ng/mL',
      decimal_places:1,
      method:'Inmunoensayo / LC-MS/MS',
      assayNotes:'LC-MS/MS referencia.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:30, upper:100 } ],
      notes:'Suficiencia habitual ≥30 ng/mL; >100 posible toxicidad.',
      sources:[{ citation:'Endocrine Society orientativo', url:'' }],
      categoryHints:['Vitaminas','Metabólico']
    },
    // ================== PERFIL ENDOCRINO / INFLAMATORIO ==================
    {
      key:'hba1c',
      canonicalName:'Hemoglobina Glicosilada (HbA1c)',
      synonyms:['hba1c','hemoglobina glicosilada','a1c'],
      unit:'%',
      decimal_places:2,
      method:'HPLC / Inmunoensayo',
      assayNotes:'Trazable NGSP / IFCC.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:4.0, upper:5.6 } ],
      notes:'5.7–6.4% prediabetes; ≥6.5% criterio diagnóstico DM.',
      sources:[{ citation:'ADA', url:'' }],
      categoryHints:['Endocrino','Metabólico']
    },
    {
      key:'tsh',
      canonicalName:'TSH',
      synonyms:['tsh','hormona estimulante tiroides','thyroid stimulating hormone'],
      unit:'µIU/mL',
      decimal_places:2,
      method:'Inmunoquimioluminiscencia',
      assayNotes:'3ra generación.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:0.4, upper:4.0 } ],
      notes:'Rango puede ajustarse por trimestre gestacional.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo']
    },
    {
      key:'t4_libre',
      canonicalName:'T4 Libre',
      synonyms:['t4 libre','ft4','free t4'],
      unit:'ng/dL',
      decimal_places:2,
      method:'Inmunoensayo',
      assayNotes:'Ultrasensible.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:0.8, upper:1.8 } ],
      notes:'Valores método dependientes.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo']
    },
    {
      key:'t4_total',
      canonicalName:'T4 Total',
      synonyms:['t4 total','tt4','total t4'],
      unit:'µg/dL',
      decimal_places:2,
      method:'Inmunoensayo',
      assayNotes:'Afectada por proteínas transportadoras.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:4.5, upper:11.2 } ],
      notes:'Interpretar junto a TSH y T4 Libre.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo']
    },
    {
      key:'t3_libre',
      canonicalName:'T3 Libre',
      synonyms:['t3 libre','ft3','free t3'],
      unit:'pg/mL',
      decimal_places:2,
      method:'Inmunoensayo',
      assayNotes:'Ultrasensible.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:2.3, upper:4.2 } ],
      notes:'Útil en hipertiroidismo.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo']
    },
    {
      key:'t3_total',
      canonicalName:'T3 Total',
      synonyms:['t3 total','tt3','total t3'],
      unit:'ng/dL',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Afectada por proteínas transportadoras.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:80, upper:200 } ],
      notes:'Apoyo diagnóstico en disfunción tiroidea.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo']
    },
    {
      key:'anti_tpo',
      canonicalName:'Anticuerpos Anti-TPO',
      synonyms:['anti tpo','anti-tpo','anti peroxidasa tiroidea','anti thyroid peroxidase'],
      unit:'UI/mL',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Cut-off dependiente del fabricante.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:0, upper:34 } ],
      notes:'Elevado en tiroiditis autoinmune.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo','Autoinmune']
    },
    {
      key:'anti_tiroglobulina',
      canonicalName:'Anticuerpos Anti-Tiroglobulina',
      synonyms:['anti tiroglobulina','anti-tiroglobulina','anti tg','anti-tg','anti thyroglobulin'],
      unit:'UI/mL',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Interpretar con Tiroglobulina.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:0, upper:115 } ],
      notes:'Elevado en tiroiditis de Hashimoto y otras autoinmunes.',
      sources:[{ citation:'Guías ATA', url:'' }],
      categoryHints:['Endocrino','Tiroideo','Autoinmune']
    },
    {
      key:'pcr',
      canonicalName:'Proteína C Reactiva',
      synonyms:['pcr','proteina c reactiva','c reactive protein','crp'],
      unit:'mg/L',
      decimal_places:2,
      method:'Inmunoturbidimetría',
      assayNotes:'Alta sensibilidad (hs) según ensayo.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:12, max:120, lower:0.0, upper:5.0 } ],
      notes:'>10 mg/L sugiere inflamación aguda significativa.',
      sources:[{ citation:'Ref. Inflamación estándar', url:'' }],
      categoryHints:['Inflamación']
    },
    {
      key:'dimero_d',
      canonicalName:'Dímero D',
      synonyms:['dimero d','dímero d','d-dimer','ddimer'],
      unit:'ng/mL FEU',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Expresar en unidades FEU.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:50, lower:0, upper:500 }, { sex:'Ambos', min:50, max:120, lower:0, upper:750 } ],
      notes:'Rango ajustado por edad >50 (edad x 10).',
      sources:[{ citation:'Guías Tromboembolismo', url:'' }],
      categoryHints:['Coagulación','Inflamación'],
      decision_points:[
        { context:'Corte estándar exclusión TEP', operator:'<=', cutoff:500, unit:'ng/mL FEU', note:'Si baja probabilidad clínica.', source:'ESC TEP' },
        { context:'Edad >50 (edad x10)', operator:'custom', cutoff:null, unit:'ng/mL FEU', note:'Umbral superior = edad x10.', source:'ESC TEP' }
      ],
      reference_notes:'Aplicar Wells/Ginebra antes de solicitar; usar ajuste por edad >50 años.'
      , en:{ name:'D-Dimer' }
    },
    {
      key:'fibrinogeno',
      canonicalName:'Fibrinógeno',
      synonyms:['fibrinogeno','fibrinógeno','fibrinogen'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Clauss',
      assayNotes:'Método funcional.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:200, upper:400 } ],
      notes:'<100 mg/dL riesgo hemorrágico; >700 asociado con inflamación.',
      sources:[{ citation:'Guías Coagulación', url:'' }],
      categoryHints:['Coagulación'],
      decision_points:[
        { context:'Riesgo hemorrágico', operator:'<', cutoff:100, unit:'mg/dL', note:'Considerar reposición crioprecipitado/plasma.', source:'Guías Coagulación' },
        { context:'Hiperfibrinogenemia', operator:'>=', cutoff:700, unit:'mg/dL', note:'Inflamación aguda marcada / riesgo trombótico.', source:'Guías Coagulación' }
      ],
      reference_notes:'Interpretar junto a plaquetas, TP/INR y aPTT en coagulopatías.'
      , en:{ name:'Fibrinogen' }
    },
    {
      key:'lactato',
      canonicalName:'Lactato',
      synonyms:['lactato','lactate'],
      unit:'mmol/L',
      decimal_places:2,
      method:'Enzimático',
      assayNotes:'Muestra arterial/venosa sin torniquete prolongado.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:0, max:120, lower:0.5, upper:2.2 } ],
      notes:'>4 mmol/L asocia hipoperfusión severa.',
      sources:[{ citation:'Sepsis Guidelines', url:'' }],
      categoryHints:['Crítico','Metabólico'],
      decision_points:[
        { context:'Hipoperfusión severa', operator:'>=', cutoff:4.0, unit:'mmol/L', note:'Asociado a shock / sepsis severa.', source:'Sepsis Surviving' },
        { context:'Objetivo reanimación', operator:'<', cutoff:2.0, unit:'mmol/L', note:'Meta frecuente control perfusión.', source:'Sepsis Surviving' }
      ],
      reference_notes:'Monitorizar tendencia seriada en sepsis o shock.'
      , en:{ name:'Lactate' }
    },
    {
      key:'troponina_i_hs',
      canonicalName:'Troponina I de Alta Sensibilidad',
      synonyms:['troponina i hs','hs-cTnI','troponina i alta sensibilidad','ctni'],
      unit:'ng/L',
      decimal_places:1,
      method:'Inmunoensayo de alta sensibilidad',
      assayNotes:'Límites sexo-específicos orientativos (p99).',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Femenino', min:18, max:120, lower:0, upper:16 }, { sex:'Masculino', min:18, max:120, lower:0, upper:34 } ],
      notes:'Interpretar con dinámica (delta) y cuadro clínico.',
      sources:[{ citation:'ESC 2023', url:'' }],
      categoryHints:['Cardíaco','Crítico'],
      decision_points:[
        { context:'Regla de exclusión IAM (0h)', operator:'<=', cutoff:5, unit:'ng/L', note:'Muy baja a las 0h con >3h de dolor torácico puede excluir IAM (depende algoritmo).', source:'ESC 2023' },
        { context:'P99 Femenino', operator:'<=', cutoff:16, unit:'ng/L', note:'Percentil 99 femenino.', source:'ESC 2023' },
        { context:'P99 Masculino', operator:'<=', cutoff:34, unit:'ng/L', note:'Percentil 99 masculino.', source:'ESC 2023' },
        { context:'Delta 1h Regla-in', operator:'>=', cutoff:12, unit:'ng/L', note:'Aumento absoluto 0–1h orienta a IAM (algoritmo 0/1h).', source:'ESC 2023' }
      ],
      reference_notes:'Usar algoritmos 0/1h o 0/2h. Delta absoluta y tiempo de evolución críticos.'
      , en:{ name:'High Sensitivity Cardiac Troponin I' }
    },
    {
      key:'troponina_t_hs',
      canonicalName:'Troponina T de Alta Sensibilidad',
      synonyms:['troponina t hs','hs-cTnT','troponina t alta sensibilidad','ctnt'],
      unit:'ng/L',
      decimal_places:1,
      method:'Inmunoensayo de alta sensibilidad',
      assayNotes:'P99 sexo-específico orientativo.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Femenino', min:18, max:120, lower:0, upper:10 }, { sex:'Masculino', min:18, max:120, lower:0, upper:14 } ],
      notes:'Utilizar algoritmos 0/1h o 0/2h.',
      sources:[{ citation:'ESC 2023', url:'' }],
      categoryHints:['Cardíaco','Crítico'],
      decision_points:[
        { context:'P99 Femenino', operator:'<=', cutoff:10, unit:'ng/L', note:'Percentil 99 femenino.', source:'ESC 2023' },
        { context:'P99 Masculino', operator:'<=', cutoff:14, unit:'ng/L', note:'Percentil 99 masculino.', source:'ESC 2023' },
        { context:'Delta 1h Regla-in', operator:'>=', cutoff:5, unit:'ng/L', note:'Aumento absoluto 0–1h orienta a IAM (algoritmo 0/1h).', source:'ESC 2023' }
      ],
      reference_notes:'Interpretar con clínica y ECG. Delta seriada esencial para IAM.'
      , en:{ name:'High Sensitivity Cardiac Troponin T' }
    },
    {
      key:'nt_probnp',
      canonicalName:'NT-proBNP',
      synonyms:['nt-probnp','ntprobnp','nt pro bnp'],
      unit:'pg/mL',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Rangos muy dependientes de edad.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:50, lower:0, upper:125 }, { sex:'Ambos', min:50, max:120, lower:0, upper:450 } ],
      notes:'Cortar >900 pg/mL sugiere IC aguda en >50 años (orientativo).',
      sources:[{ citation:'Guías Insuficiencia Cardíaca', url:'' }],
      categoryHints:['Cardíaco'],
      decision_points:[
        { context:'Exclusión IC aguda (<50a)', operator:'<', cutoff:300, unit:'pg/mL', note:'<300 hace improbable IC aguda.', source:'ESC HF' },
        { context:'Regla-in IC aguda (50-75a)', operator:'>=', cutoff:900, unit:'pg/mL', note:'Con clínica apoya IC.', source:'ESC HF' },
        { context:'Regla-in IC aguda (>75a)', operator:'>=', cutoff:1800, unit:'pg/mL', note:'Umbral mayor en >75.', source:'ESC HF' }
      ],
      reference_notes:'Interpretar con función renal, edad y obesidad (que puede bajar niveles).'
      , en:{ name:'NT-proBNP' }
    },
    {
      key:'psa_total',
      canonicalName:'PSA Total',
      synonyms:['psa','psa total','antigeno prostatico especifico','antígeno prostático específico'],
      unit:'ng/mL',
      decimal_places:2,
      method:'Inmunoensayo',
      assayNotes:'Evitar tacto rectal/ejaculación 48h previas.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Masculino', min:40, max:50, lower:0.00, upper:2.5 },
        { sex:'Masculino', min:50, max:60, lower:0.00, upper:3.5 },
        { sex:'Masculino', min:60, max:70, lower:0.00, upper:4.5 },
        { sex:'Masculino', min:70, max:120, lower:0.00, upper:6.5 }
      ],
      notes:'Valores ajustados por edad.',
      sources:[{ citation:'Ref. Urología estándar', url:'' }],
      categoryHints:['Endocrino','Reproductivo','Oncológico'],
      decision_points:[
        { context:'Riesgo elevado', operator:'>=', cutoff:4.0, unit:'ng/mL', note:'Umbral clásico para ampliar estudio.', source:'Urología' },
        { context:'Alto riesgo', operator:'>=', cutoff:10.0, unit:'ng/mL', note:'Mayor probabilidad neoplasia significativa.', source:'Urología' }
      ],
      reference_notes:'Considerar PSA libre/total y densidad prostática para refinar riesgo.'
      , en:{ name:'Total PSA' }
    },
    // ================== ANDRÓGENOS / MARCADORES ONCOLÓGICOS ==================
    {
      key:'shbg',
      canonicalName:'Globulina Fijadora de Hormonas Sexuales (SHBG)',
      synonyms:['shbg','globulina fijadora hormonas sexuales'],
      unit:'nmol/L',
      decimal_places:1,
      method:'Inmunoensayo',
      assayNotes:'Afectada por estrógenos, tiroideas y estado hepático.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Masculino', min:18, max:120, lower:10, upper:57 },
        { sex:'Femenino', min:18, max:50, lower:18, upper:114 },
        { sex:'Femenino', min:50, max:120, lower:20, upper:122 }
      ],
      notes:'Empleada para calcular testosterona libre.',
      sources:[{ citation:'Ref. Andrógenos', url:'' }],
      categoryHints:['Endocrino','Reproductivo']
    },
    {
      key:'testosterona_libre_calculada',
      canonicalName:'Testosterona Libre Calculada',
      synonyms:['testosterona libre','free testosterone','testosterona libre calculada'],
      unit:'pg/mL',
      decimal_places:1,
      method:'Cálculo (Vermeulen)',
      assayNotes:'Derivada de testosterona total, SHBG y albúmina.',
      validated:true,
      lockAI:true,
      groups:[
        { sex:'Masculino', min:18, max:120, lower:47, upper:244 },
        { sex:'Femenino', min:18, max:120, lower:0.5, upper:8.0 }
      ],
      notes:'Valores orientativos; usar LC-MS/MS para confirmación.',
      sources:[{ citation:'Ref. Andrógenos', url:'' }],
      categoryHints:['Endocrino','Reproductivo']
    },
    {
      key:'indice_androgeno_libre',
      canonicalName:'Índice Andrógeno Libre',
      synonyms:['indice androgeno libre','ial','free androgen index'],
      unit:'%',
      decimal_places:1,
      method:'Cálculo (TT / SHBG * 100)',
      assayNotes:'Requiere valores fiables de TT y SHBG.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Femenino', min:18, max:120, lower:0.5, upper:11.0 }, { sex:'Masculino', min:18, max:120, lower:14, upper:95 } ],
      notes:'Elevado sugiere hiperandrogenismo (F); bajo hipogonadismo (M).',
      sources:[{ citation:'Ref. Andrógenos', url:'' }],
      categoryHints:['Endocrino','Reproductivo']
    },
    {
      key:'cea',
      canonicalName:'CEA',
      synonyms:['cea','antigeno carcinoembrionario','antígeno carcinoembrionario'],
      unit:'ng/mL',
      decimal_places:1,
      method:'Inmunoensayo',
      assayNotes:'Fumar puede elevar moderadamente.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.0, upper:3.0 } ],
      notes:'Umbral oncológico frecuentemente >5 ng/mL.',
      sources:[{ citation:'Ref. Oncología', url:'' }],
      categoryHints:['Oncológico']
    },
    {
      key:'ca_125',
      canonicalName:'CA 125',
      synonyms:['ca125','ca-125'],
      unit:'U/mL',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Aumenta en condiciones benignas (endometriosis, menstruación).',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Femenino', min:18, max:120, lower:0, upper:35 } ],
      notes:'Monitorización cáncer de ovario.',
      sources:[{ citation:'Ref. Oncología', url:'' }],
      categoryHints:['Oncológico']
    },
    {
      key:'ca_19_9',
      canonicalName:'CA 19-9',
      synonyms:['ca19-9','ca 19 9'],
      unit:'U/mL',
      decimal_places:0,
      method:'Inmunoensayo',
      assayNotes:'Elevaciones leves en patologías benignas biliares.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0, upper:37 } ],
      notes:'Monitorización cáncer pancreático / biliar.',
      sources:[{ citation:'Ref. Oncología', url:'' }],
      categoryHints:['Oncológico']
    },
    {
      key:'afp',
      canonicalName:'Alfa-Fetoproteína (AFP)',
      synonyms:['afp','alfa fetoproteina','alfa-fetoproteina'],
      unit:'ng/mL',
      decimal_places:1,
      method:'Inmunoensayo',
      assayNotes:'Interpretar con imagen hepática.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.0, upper:10.0 } ],
      notes:'Elevaciones marcadas en hepatocarcinoma y tumores germinales.',
      sources:[{ citation:'Ref. Oncología', url:'' }],
      categoryHints:['Oncológico']
    },
    {
      key:'beta_hcg',
      canonicalName:'Beta-hCG',
      synonyms:['beta hcg','β-hcg','bhcg','beta-hcg'],
      unit:'mIU/mL',
      decimal_places:1,
      method:'Inmunoensayo',
      assayNotes:'Embarazo temprano y marcadores tumorales.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Femenino', min:18, max:50, lower:0.0, upper:5.0 }, { sex:'Femenino', min:50, max:120, lower:0.0, upper:8.0 }, { sex:'Masculino', min:18, max:120, lower:0.0, upper:5.0 } ],
      notes:'Valores gestacionales normales superan ampliamente estos límites basales.',
      sources:[{ citation:'Ref. Oncología / Obstetricia', url:'' }],
      categoryHints:['Oncológico','Endocrino','Reproductivo']
    }
    ,
    // ================== COAGULACIÓN AVANZADA ==================
    {
      key:'tp_protrombina',
      canonicalName:'Tiempo de Protrombina (TP)',
      synonyms:['tp','tiempo de protrombina','pt','prothrombin time'],
      unit:'s',
      decimal_places:1,
      method:'Coagulométrico',
      assayNotes:'Reagente tromboplastina; informar también INR.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:11.0, upper:15.0 } ],
      notes:'Rango depende del ISI del reactivo.',
      sources:[{ citation:'Guías Coagulación', url:'' }],
      categoryHints:['Coagulación']
    },
    {
      key:'inr',
      canonicalName:'INR',
      synonyms:['inr','razon normalizada internacional'],
      unit:'',
      decimal_places:2,
      method:'Cálculo (ISI)',
      assayNotes:'(TP paciente / TP normal)^ISI.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.8, upper:1.2 } ],
      notes:'Objetivos terapéuticos habituales: 2.0–3.0 o 2.5–3.5 según indicación.',
      sources:[{ citation:'Guías Anticoagulación', url:'' }],
      categoryHints:['Coagulación']
    },
    {
      key:'aptt',
      canonicalName:'Tiempo de Tromboplastina Parcial Activado (aPTT)',
      synonyms:['aptt','tpta','tiempo tromboplastina parcial activado','ptt'],
      unit:'s',
      decimal_places:1,
      method:'Coagulométrico',
      assayNotes:'Activador (sílice/caolín) y fosfolípidos.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:25.0, upper:35.0 } ],
      notes:'Rangos dependen del reactivo y equipo.',
      sources:[{ citation:'Guías Coagulación', url:'' }],
      categoryHints:['Coagulación']
    },
    {
      key:'fibrinogeno',
      canonicalName:'Fibrinógeno',
      synonyms:['fibrinogeno','fibrinógeno','fibrinogen'],
      unit:'mg/dL',
      decimal_places:0,
      method:'Clauss',
      assayNotes:'Método funcional.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:200, upper:400 } ],
      notes:'<100 mg/dL riesgo hemorrágico; >700 asociado con inflamación.',
      sources:[{ citation:'Guías Coagulación', url:'' }],
      categoryHints:['Coagulación'],
      decision_points:[
        { context:'Riesgo hemorrágico', operator:'<', cutoff:100, unit:'mg/dL', note:'Considerar reposición crioprecipitado/plasma.', source:'Guías Coagulación' },
        { context:'Hiperfibrinogenemia', operator:'>=', cutoff:700, unit:'mg/dL', note:'Inflamación aguda marcada / riesgo trombótico.', source:'Guías Coagulación' }
      ],
      reference_notes:'Interpretar junto a plaquetas, TP/INR y aPTT en coagulopatías.'
    },
    // ================== AUTOINMUNIDAD ADICIONAL ==================
    {
      key:'ana_titulo',
      canonicalName:'ANA (Título)',
      synonyms:['ana','anticuerpos antinucleares','ana titulo','antinuclear antibodies'],
      unit:'Título',
      decimal_places:0,
      method:'Inmunofluorescencia (HEp-2)',
      assayNotes:'Reportar patrón (homogéneo, moteado, etc.).',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0, upper:80 } ],
      notes:'Cut-off habitual ≥1:80 (laboratorio dependiente).',
      sources:[{ citation:'Guías Autoinmunidad', url:'' }],
      categoryHints:['Autoinmune']
    },
    {
      key:'factor_reumatoide',
      canonicalName:'Factor Reumatoide',
      synonyms:['factor reumatoide','fr','rheumatoid factor'],
      unit:'IU/mL',
      decimal_places:1,
      method:'Nefelometría / Turbidimetría',
      assayNotes:'Valores levemente elevados en otras patologías.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.0, upper:14.0 } ],
      notes:'>14 IU/mL sugiere positividad (interpretar con clínica).',
      sources:[{ citation:'Guías Reumatología', url:'' }],
      categoryHints:['Autoinmune']
    },
    {
      key:'anti_ccp',
      canonicalName:'Anticuerpos Anti-CCP',
      synonyms:['anti ccp','anticcp','anticuerpos anti ccp','anti-ccp'],
      unit:'U/mL',
      decimal_places:1,
      method:'Inmunoensayo',
      assayNotes:'Alta especificidad para AR.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.0, upper:20.0 } ],
      notes:'>20 U/mL sugiere AR (método dependiente).',
      sources:[{ citation:'Guías Reumatología', url:'' }],
      categoryHints:['Autoinmune']
    },
    // ================== SEROLOGÍAS ==================
    {
      key:'hbsag',
      canonicalName:'HBsAg',
      synonyms:['hbsag','antigeno de superficie hepatitis b','hepatitis b surface antigen'],
      unit:'Índice',
      decimal_places:2,
      method:'Inmunoensayo',
      assayNotes:'Reportar reactivo / no reactivo.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.00, upper:0.99 } ],
      notes:'≥1.0 reactivo (sujeto a método).',
      sources:[{ citation:'Guías Hepatitis B', url:'' }],
      categoryHints:['Serológico','Infeccioso']
    },
    {
      key:'anti_hbs',
      canonicalName:'Anti-HBs',
      synonyms:['anti hbs','anti-hbs','anticuerpos anti hbs'],
      unit:'mIU/mL',
      decimal_places:1,
      method:'Inmunoensayo',
      assayNotes:'Respuesta vacunal o infección pasada.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.0, upper:9.9 } ],
      notes:'≥10 mIU/mL protección aceptada.',
      sources:[{ citation:'Guías Hepatitis B', url:'' }],
      categoryHints:['Serológico','Infeccioso']
    },
    {
      key:'anti_hcv',
      canonicalName:'Anti-HCV',
      synonyms:['anti hcv','anti-hcv','anticuerpos anti hcv'],
      unit:'Índice',
      decimal_places:2,
      method:'Inmunoensayo',
      assayNotes:'Resultados reactivo deben confirmarse (RNA).',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.00, upper:0.99 } ],
      notes:'≥1.0 reactivo (confirmar).',
      sources:[{ citation:'Guías Hepatitis C', url:'' }],
      categoryHints:['Serológico','Infeccioso']
    },
    {
      key:'vih_ag_ac',
      canonicalName:'VIH Ag/Ac (Combo)',
      synonyms:['vih ag ac','vih combo','hiv ag ab','hiv combo'],
      unit:'Índice',
      decimal_places:2,
      method:'Inmunoensayo 4ta gen',
      assayNotes:'Detección combinada p24 + anticuerpos.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0.00, upper:0.99 } ],
      notes:'≥1.0 reactivo (repetir y confirmar).',
      sources:[{ citation:'Guías VIH', url:'' }],
      categoryHints:['Serológico','Infeccioso']
    },
    {
      key:'vdrl_rpr',
      canonicalName:'VDRL / RPR (Título)',
      synonyms:['vdrl','rpr','vdrl rpr','titulo vdrl'],
      unit:'Título',
      decimal_places:0,
      method:'Floculación',
      assayNotes:'Informar reactivo y dilución máxima.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:0, upper:0 } ],
      notes:'No reactivo esperado en individuos sanos.',
      sources:[{ citation:'Guías Sífilis', url:'' }],
      categoryHints:['Serológico','Infeccioso']
    },
    // ================== GASES ARTERIALES ==================
    {
      key:'ph_arterial',
      canonicalName:'pH Arterial',
      synonyms:['ph arterial','arterial ph'],
      unit:'pH',
      decimal_places:2,
      method:'Potenciométrico',
      assayNotes:'Muestra arterial anaerobia.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:7.35, upper:7.45 } ],
      notes:'Acidemia <7.35; alcalemia >7.45.',
      sources:[{ citation:'Ref. Gases Arteriales', url:'' }],
      categoryHints:['Gases Arteriales','Ácido-Base']
    },
    {
      key:'pco2_arterial',
      canonicalName:'pCO2 Arterial',
      synonyms:['pco2 arterial','arterial pco2'],
      unit:'mmHg',
      decimal_places:1,
      method:'Electrodo Severinghaus',
      assayNotes:'Control temperatura 37°C.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:35, upper:45 } ],
      notes:'Hipocapnia <35; hipercapnia >45.',
      sources:[{ citation:'Ref. Gases Arteriales', url:'' }],
      categoryHints:['Gases Arteriales','Ácido-Base']
    },
    {
      key:'po2_arterial',
      canonicalName:'pO2 Arterial',
      synonyms:['po2 arterial','arterial po2'],
      unit:'mmHg',
      decimal_places:0,
      method:'Electrodo Clark',
      assayNotes:'Aire ambiente (FiO2 0.21).',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:80, upper:100 } ],
      notes:'Valores disminuyen con edad y altitud.',
      sources:[{ citation:'Ref. Gases Arteriales', url:'' }],
      categoryHints:['Gases Arteriales','Ácido-Base']
    },
    {
      key:'hco3_arterial',
      canonicalName:'HCO3- (Bicarbonato Arterial)',
      synonyms:['hco3 arterial','bicarbonato arterial','arterial hco3'],
      unit:'mmol/L',
      decimal_places:1,
      method:'Calculado / Potenciométrico',
      assayNotes:'Derivado de ecuación Henderson-Hasselbalch.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:22, upper:26 } ],
      notes:'Metabólico: <22 acidosis, >26 alcalosis.',
      sources:[{ citation:'Ref. Gases Arteriales', url:'' }],
      categoryHints:['Gases Arteriales','Ácido-Base']
    },
    {
      key:'saturacion_o2_arterial',
      canonicalName:'Saturación O2 Arterial',
      synonyms:['saturacion o2 arterial','sat o2 arterial','saO2','sao2'],
      unit:'%',
      decimal_places:1,
      method:'Cooximetría',
      assayNotes:'Debe correlacionar con pulsoximetría.',
      validated:true,
      lockAI:true,
      groups:[ { sex:'Ambos', min:18, max:120, lower:95, upper:100 } ],
      notes:'Hipoxemia significativa <90%.',
      sources:[{ citation:'Ref. Gases Arteriales', url:'' }],
      categoryHints:['Gases Arteriales','Ácido-Base']
    }
  ]
};
